apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: sac-deploy-task
spec:
  inputs:
    resources:
      - name: git-source-sac
        type: git
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
  steps:
  - name: deploy-policies
    image: lachlanevenson/k8s-kubectl
    command: ["/bin/bash"]
    args:
      - -c
      - |
        for yaml in *.yaml;do
          echo "Creating $yaml policy."
          kubectl create -f $yaml
        done
