apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: sac-deploy-taskrun
spec:
  serviceAccountName: pipeline
  taskRef:
    name: sac-deploy-task
  inputs:
    resources:
      - name: git-source-sac
        resourceRef:
          name: git-source-sac