apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: motd-build-taskrun
spec:
  serviceAccountName: pipeline-account
  taskRef:
    name: motd-build-task
  inputs:
    resources:
      - name: git-source-motd
        resourceRef:
          name: git-source-motd
      - name: docker-image-motd
        resourceRef:
            name: docker-image-motd
    params:
    - name: BUILDER_IMAGE
      value: "quay.io/buildah/stable:v1.12.0"
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"