apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: motd-application
  namespace: motd-mcm-resources
spec:
  selector:
    matchLabels:
      purpose: motd
  componentKinds:
  - group: app.ibm.com
    kind: Subscription